apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "azdo-agent.fullname" . }}
  labels:
    {{- include "azdo-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.diskSize }}